




// constants.ts

import { Dialect, Language, StudentGoal, Subject, DifficultyLevel, LibraryItemType } from './types';

export const LANGUAGES = [Language.EN, Language.VI, Language.ZH, Language.FR];

export const STUDENT_GOALS = [StudentGoal.GOOD, StudentGoal.EXCELLENT, StudentGoal.OUTSTANDING];

export const GRADES = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

export const SUBJECTS = [
    Subject.MATH,
    Subject.LITERATURE,
    Subject.PHYSICS,
    Subject.CHEMISTRY,
    Subject.BIOLOGY,
    Subject.HISTORY,
    Subject.GEOGRAPHY,
    Subject.ENGLISH,
    Subject.TECHNOLOGY,
    Subject.CIVIC_EDUCATION,
    Subject.INFORMATICS,
    Subject.NATURAL_SCIENCES,
];

export const DIFFICULTY_LEVELS = [
    DifficultyLevel.RECOGNITION,
    DifficultyLevel.COMPREHENSION,
    DifficultyLevel.APPLICATION
];

export const TEXTBOOKS = [
    'none',
    'canh_dieu',
    'chan_troi_sang_tao',
    'ket_noi_tri_thuc',
    'other',
];

export const STORAGE_LIMIT_BYTES = 1 * 1024 * 1024; // 1MB

export const LOCALIZATION_STRINGS: { [key in Language]: { [key: string]: string } } = {
  [Language.EN]: {
    slogan: 'Unlocking knowledge, shaping the future.',
    im_a: "I'm a...",
    student: 'Student',
    teacher: 'Teacher',
    select_goal: 'Select Your Goal',
    good_student: 'Good Student',
    excellent_student: 'Excellent Student',
    outstanding_student: 'Outstanding Student',
    summarize: 'Summarize',
    summarizer: 'Summarizer',
    exam_generator: 'Exam Generator',
    ai_assistant: 'AI Assistant',
    translator: 'Translator',
    slide_generator: 'Slide Generator',
    learning_path: 'Learning Path',
    question_analysis: 'Question Analysis',
    safety_guide: 'Safety Guide',
    upload_file: 'Upload File',
    file_placeholder: 'Upload a file (PDF, image, audio, video)',
    choose_file: 'Choose File',
    no_file_chosen: 'No file chosen',
    generating: 'Generating...',
    summary_placeholder: 'Your generated summary, mind map, and flashcards will appear here.',
    mind_map: 'Mind Map',
    flashcards: 'Flashcards',
    source_language: 'Source Language',
    target_language: 'Target Language',
    source_text_placeholder: 'Enter text to translate...',
    copy_text: 'Copy',
    copied: 'Copied!',
    copy_as_text: 'Copy as Text',
    copy_for_word: 'Copy for Word',
    converting: 'Converting...',
    swap_languages: 'Swap Languages',
    translate_button: 'Translate',
    presentation_topic: 'Presentation Topic',
    topic_placeholder: 'e.g., "The History of AI"',
    upload_template: 'Upload Template (Optional)',
    generate_slides: 'Generate Slides',
    slide_placeholder: 'Your generated slide content will appear here.',
    grade: 'Grade',
    subject: 'Subject',
    generate_plan: 'Generate Plan',
    completed: 'Completed',
    current_lesson: 'Current Lesson',
    locked: 'Locked',
    plan_placeholder: 'Generate a learning plan to get started.',
    lesson_placeholder: 'Select a lesson to view its content.',
    mark_complete: "Mark as Complete & Next",
    exam_topic: 'Exam Topic',
    multiple_choice: 'Multiple Choice',
    essay: 'Essay',
    generate_exam: 'Generate Exam',
    exam_placeholder: 'Your generated exam questions will appear here.',
    send_message: 'Send',
    teacher_chatbot_greeting: 'Hello! I am your AI study companion. I will help you think and solve problems on your own. I will strictly follow the 2018 General Education Program. What do you need help with today?',
    teacher_chatbot_placeholder: 'Ask a question (e.g., "How do I solve this?", "Explain this concept")...',
    attach_file: 'Attach File',
    file_attached: 'File attached:',
    remove_file: 'Remove file',
    start_recording: 'Start Recording',
    stop_recording: 'Stop Recording',
    voice_unsupported: 'Voice input is not supported by your browser.',
    select_dialect: 'Select Dialect',
    north: 'North',
    central: 'Central',
    south: 'South',
    textbook: 'Textbook',
    upload_matrix: 'Upload Matrix',
    manual_textbook_placeholder: 'Enter textbook name...',
    question_analysis_title: 'Similar Exercise Generator',
    generate_similar_exercises: 'Generate Similar Exercises',
    upload_question_file: 'Upload a question file (image, PDF)',
    similar_exercises_placeholder: 'Your generated similar exercises will appear here.',
    analysis_of_original_question: 'Analysis of the Original Question',
    similar_practice_exercises: 'Similar Practice Exercises',
    read_aloud: 'Read Aloud',
    exam_duration: 'Exam Duration (minutes)',
    num_multiple_choice: 'Total Multiple Choice Qs',
    num_essay: 'Essay Qs by Difficulty',
    difficulty_level: 'Difficulty Level',
    recognition: 'Recognition',
    comprehension: 'Comprehension',
    application: 'Application',
    mc_difficulty_breakdown: 'MC Qs by Difficulty',
    mc_sum_error: 'Sum of MC counts must equal total.',
    review_topic: 'Review Topic',
    generate_review_exercises: 'Generate Exercises',
    review_placeholder: 'Your generated review exercises will appear here.',
    go_home: 'Go Home',
    library: 'Library',
    documents: 'Documents',
    save_to_library: 'Save to Library',
    save_to_documents: 'Save to Documents',
    saved: 'Saved!',
    library_empty: 'Your library is empty. Save generated content to see it here.',
    documents_empty: 'You have no saved documents. Save generated content to see it here.',
    delete: 'Delete',
    view: 'View',
    close: 'Close',
    confirm_delete_title: 'Confirm Deletion',
    confirm_delete_message: 'Are you sure you want to delete this item?',
    storage_full: 'Storage is full. Please delete some items to save new content.',
    storage_usage: 'Storage Usage',
    item_name_placeholder: 'Enter a name for this item...',
    save: 'Save',
    zoom_in: 'Zoom In',
    zoom_out: 'Zoom Out',
    reset_zoom: 'Reset Zoom',
    specialized_review: 'Specialized Review',
    numbers: 'Numbers & Algebra',
    geometry: 'Geometry',
    both: 'Both',
    sub_subjects: 'Sub-subjects',
    none: 'None',
    canh_dieu: 'Cánh diều',
    chan_troi_sang_tao: 'Chân trời sáng tạo',
    ket_noi_tri_thuc: 'Kết nối tri thức',
    other: 'Other (manual input)',
    image_generation_error: 'Image generation failed',
    unsafe_content_error: 'This content is unsuitable for learning purposes. Please ask another question.',
    terms_title: 'Commitment to Use',
    terms_content: 'I commit to using AI to support learning, not to cheat, not to copy, and not to enter personal information.',
    i_agree: 'I Agree',
    continue: 'Start Using',
    account_locked_title: 'Account Locked',
    account_locked_message: 'Your account has been locked by the administrator.',
    lock_mild_message: 'Your account is temporarily locked for 3 days due to safety violations.',
    lock_severe_message: 'Your account is locked for 1 month due to severe violations (e.g., requesting passwords, cheating).',
    unlock_at: 'Account will unlock at:',
    contact_support: 'Reload Page',
    safety_guide_title: 'Learn to use AI correctly',
    sg_topic_1: 'Effective Questioning',
    sg_desc_1: 'Thinking & Inquiry',
    sg_topic_2: 'Why not copy?',
    sg_desc_2: 'Anti-rote learning',
    sg_topic_3: 'Fact Verification',
    sg_desc_3: 'Anti-misinformation',
    sg_topic_4: 'Data Privacy',
    sg_desc_4: 'Cybersecurity',
    ethics_reminder: '\n\n*Note: This suggestion is for reference only. Rewrite it in your own understanding and cite sources if used.*',
    login: 'Login',
    register: 'Register',
    username: 'Username',
    password: 'Password',
    admin_password: 'Admin Password',
    enter_admin_mode: 'Enter Admin Mode',
    admin_dashboard: 'Admin Dashboard',
    user_list: 'User List',
    status: 'Status',
    actions: 'Actions',
    active: 'Active',
    unlock: 'Unlock',
    lock: 'Lock',
    logout: 'Logout',
    back_to_app: 'Back to App',
    login_success: 'Login successful!',
    register_success: 'Registration successful! Please login.',
    user_exists: 'Username already exists.',
    invalid_credentials: 'Invalid username or password.',
    fill_all_fields: 'Please fill in all fields.',
    admin_login_failed: 'Invalid Admin Credentials.',
    confirm_lock: 'Lock this user?',
    confirm_delete_user: 'Delete this user?',
    change_admin_password: 'My Profile (Update Credentials)',
    new_password: 'New Password',
    save_password: 'Update',
    password_changed: 'Credentials updated successfully!',
    current_feature: 'Current Feature',
    last_activity: 'Last Activity',
    lock_duration: 'Lock Duration',
    select_lock_duration: 'Select Lock Duration',
    duration_15m: '15 Minutes',
    duration_1h: '1 Hour',
    duration_1d: '1 Day',
    duration_3d: '3 Days',
    duration_7d: '1 Week',
    duration_30d: '1 Month',
    duration_permanent: 'Permanent (100 years)',
    cancel: 'Cancel',
    admin_locked: 'Admin Locked',
    admin_management: 'Admin Management',
    create_admin: 'Create Admin',
    super_admin: 'Super Admin',
    normal_admin: 'Admin',
    role: 'Role',
    audit_logs: 'Audit Logs',
    log_action: 'Action',
    log_target: 'Target',
    log_timestamp: 'Time',
    new_username: 'New Username',
    create_admin_success: 'Admin created successfully.',
    admin_exists: 'Admin username already exists.',
    confirm_delete_admin: 'Delete this admin?',
    deleted_users: 'Deleted Users',
    restore: 'Restore',
    deleted_by: 'Deleted By',
    locked_by: 'Locked By',
    locked_by_admin: 'Locked by Admin:',
    [Subject.MATH]: 'Math',
    [Subject.LITERATURE]: 'Literature',
    [Subject.PHYSICS]: 'Physics',
    [Subject.CHEMISTRY]: 'Chemistry',
    [Subject.BIOLOGY]: 'Biology',
    [Subject.HISTORY]: 'History',
    [Subject.GEOGRAPHY]: 'Geography',
    [Subject.ENGLISH]: 'English',
    [Subject.TECHNOLOGY]: 'Technology',
    [Subject.CIVIC_EDUCATION]: 'Civic Education',
    [Subject.INFORMATICS]: 'Informatics',
    [Subject.NATURAL_SCIENCES]: 'Natural Sciences',
    [LibraryItemType.SUMMARY]: 'Summary',
    [LibraryItemType.EXAM]: 'Exam',
    [LibraryItemType.REVIEW_EXERCISES]: 'Review Exercises',
    [LibraryItemType.SIMILAR_EXERCISES]: 'Similar Exercises',
  },
  [Language.VI]: {
    slogan: 'Khai mở tri thức, định hình tương lai.',
    im_a: 'Tôi là...',
    student: 'Học sinh',
    teacher: 'Giáo viên',
    select_goal: 'Chọn Mục tiêu của bạn',
    good_student: 'Học sinh Khá',
    excellent_student: 'Học sinh Giỏi',
    outstanding_student: 'Học sinh Xuất sắc',
    summarize: 'Tóm tắt',
    summarizer: 'Trình tóm tắt',
    exam_generator: 'Tạo Đề thi',
    ai_assistant: 'Trợ lý AI',
    translator: 'Dịch thuật',
    slide_generator: 'Tạo Slide',
    learning_path: 'Lộ trình học tập',
    question_analysis: 'Phân tích Câu hỏi',
    safety_guide: 'HDSD An toàn',
    upload_file: 'Tải tệp lên',
    file_placeholder: 'Tải lên tệp (PDF, ảnh, âm thanh, video)',
    choose_file: 'Chọn tệp',
    no_file_chosen: 'Chưa chọn tệp nào',
    generating: 'Đang tạo...',
    summary_placeholder: 'Bản tóm tắt, sơ đồ tư duy và flashcard của bạn sẽ xuất hiện ở đây.',
    mind_map: 'Sơ đồ tư duy',
    flashcards: 'Thẻ ghi nhớ',
    source_language: 'Ngôn ngữ nguồn',
    target_language: 'Ngôn ngữ đích',
    source_text_placeholder: 'Nhập văn bản cần dịch...',
    copy_text: 'Sao chép',
    copied: 'Đã sao chép!',
    copy_as_text: 'Sao chép dạng Chữ',
    copy_for_word: 'Sao chép cho Word',
    converting: 'Đang chuyển đổi...',
    swap_languages: 'Hoán đổi ngôn ngữ',
    translate_button: 'Dịch',
    presentation_topic: 'Chủ đề bài thuyết trình',
    topic_placeholder: 'ví dụ: "Lịch sử của AI"',
    upload_template: 'Tải lên mẫu (Tùy chọn)',
    generate_slides: 'Tạo Slide',
    slide_placeholder: 'Nội dung slide được tạo của bạn sẽ xuất hiện ở đây.',
    grade: 'Lớp',
    subject: 'Môn học',
    generate_plan: 'Tạo kế hoạch',
    completed: 'Đã hoàn thành',
    current_lesson: 'Bài học hiện tại',
    locked: 'Đã khóa',
    plan_placeholder: 'Tạo một kế hoạch học tập để bắt đầu.',
    lesson_placeholder: 'Chọn một bài học để xem nội dung.',
    mark_complete: "Đánh dấu Hoàn thành & Tiếp theo",
    exam_topic: 'Chủ đề bài kiểm tra',
    multiple_choice: 'Trắc nghiệm',
    essay: 'Tự luận',
    generate_exam: 'Tạo Đề thi',
    exam_placeholder: 'Câu hỏi thi được tạo của bạn sẽ xuất hiện ở đây.',
    send_message: 'Gửi',
    teacher_chatbot_greeting: 'Xin chào! Tôi là bạn đồng hành học tập AI của bạn. Tôi sẽ giúp bạn tư duy và tự giải quyết vấn đề, tuân thủ chặt chẽ Chương trình Giáo dục Phổ thông 2018. Bạn cần giúp đỡ gì hôm nay?',
    teacher_chatbot_placeholder: 'Đặt câu hỏi (vd: "Làm sao để giải bài này?", "Giải thích khái niệm này")...',
    attach_file: 'Đính kèm tệp',
    file_attached: 'Tệp đính kèm:',
    remove_file: 'Xóa tệp',
    start_recording: 'Bắt đầu ghi âm',
    stop_recording: 'Dừng ghi âm',
    voice_unsupported: 'Trình duyệt của bạn không hỗ trợ nhập liệu bằng giọng nói.',
    select_dialect: 'Chọn vùng miền',
    north: 'Bắc',
    central: 'Trung',
    south: 'Nam',
    textbook: 'Sách giáo khoa',
    upload_matrix: 'Tải lên ma trận',
    manual_textbook_placeholder: 'Nhập tên sách giáo khoa...',
    question_analysis_title: 'Trình tạo Bài tập Tương tự',
    generate_similar_exercises: 'Tạo bài tập tương tự',
    upload_question_file: 'Tải lên tệp câu hỏi (ảnh, PDF)',
    similar_exercises_placeholder: 'Các bài tập tương tự được tạo sẽ xuất hiện ở đây.',
    analysis_of_original_question: 'Phân tích câu hỏi gốc',
    similar_practice_exercises: 'Các bài tập tương tự',
    read_aloud: 'Đọc to',
    exam_duration: 'Thời gian (phút)',
    num_multiple_choice: 'Tổng số câu TN',
    num_essay: 'Số câu TL theo độ khó',
    difficulty_level: 'Mức độ khó',
    recognition: 'Nhận biết',
    comprehension: 'Thông hiểu',
    application: 'Vận dụng',
    mc_difficulty_breakdown: 'Số câu TN theo độ khó',
    mc_sum_error: 'Tổng số câu theo độ khó phải bằng tổng số câu TN.',
    review_topic: 'Chủ đề ôn tập',
    generate_review_exercises: 'Tạo bài tập',
    review_placeholder: 'Bài tập ôn tập của bạn sẽ xuất hiện ở đây.',
    go_home: 'Về trang chủ',
    library: 'Thư viện',
    documents: 'Tài liệu',
    save_to_library: 'Lưu vào Thư viện',
    save_to_documents: 'Lưu vào Tài liệu',
    saved: 'Đã lưu!',
    library_empty: 'Thư viện của bạn trống. Lưu nội dung đã tạo để xem tại đây.',
    documents_empty: 'Bạn chưa có tài liệu nào. Lưu nội dung đã tạo để xem tại đây.',
    delete: 'Xóa',
    view: 'Xem',
    close: 'Đóng',
    confirm_delete_title: 'Xác nhận Xóa',
    confirm_delete_message: 'Bạn có chắc chắn muốn xóa mục này không?',
    storage_full: 'Bộ nhớ đã đầy. Vui lòng xóa bớt các mục để lưu nội dung mới.',
    storage_usage: 'Dung lượng lưu trữ',
    item_name_placeholder: 'Nhập tên cho mục này...',
    save: 'Lưu',
    zoom_in: 'Phóng to',
    zoom_out: 'Thu nhỏ',
    reset_zoom: 'Đặt lại',
    specialized_review: 'Ôn tập chuyên đề',
    numbers: 'Số học',
    geometry: 'Hình học',
    both: 'Cả hai',
    sub_subjects: 'Các môn thành phần',
    none: 'Không',
    canh_dieu: 'Cánh diều',
    chan_troi_sang_tao: 'Chân trời sáng tạo',
    ket_noi_tri_thuc: 'Kết nối tri thức',
    other: 'Khác (tự nhập)',
    image_generation_error: 'Tạo ảnh thất bại',
    unsafe_content_error: 'Nội dung này không phù hợp mục đích học tập. Vui lòng đặt câu hỏi khác.',
    terms_title: 'Cam kết sử dụng',
    terms_content: 'Tôi cam kết sử dụng AI để hỗ trợ học tập, không gian lận, không sao chép và không nhập thông tin cá nhân.',
    i_agree: 'Tôi đồng ý',
    continue: 'Bắt đầu sử dụng',
    account_locked_title: 'Tài khoản bị khóa',
    account_locked_message: 'Tài khoản của bạn đã bị khóa bởi quản trị viên.',
    lock_mild_message: 'Tài khoản bị tạm khóa 3 ngày do vi phạm an toàn.',
    lock_severe_message: 'Tài khoản bị khóa 1 tháng do vi phạm nghiêm trọng (VD: yêu cầu tạo mật khẩu, gian lận).',
    unlock_at: 'Mở khóa vào lúc:',
    contact_support: 'Tải lại trang',
    safety_guide_title: 'Học sử dụng AI đúng cách',
    sg_topic_1: 'Cách đặt câu hỏi hiệu quả',
    sg_desc_1: 'Tư duy truy vấn',
    sg_topic_2: 'Vì sao không nên copy',
    sg_desc_2: 'Chống học vẹt',
    sg_topic_3: 'Kiểm chứng thông tin',
    sg_desc_3: 'Chống tin giả',
    sg_topic_4: 'Bảo mật dữ liệu cá nhân',
    sg_desc_4: 'An ninh mạng',
    ethics_reminder: '\n\n*Gợi ý này chỉ là tham khảo. Hãy viết lại theo ý hiểu của em và trích dẫn nếu sử dụng.*',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    username: 'Tên đăng nhập',
    password: 'Mật khẩu',
    admin_password: 'Mật khẩu Quản trị viên',
    enter_admin_mode: 'Vào chế độ Quản trị',
    admin_dashboard: 'Bảng điều khiển Admin',
    user_list: 'Danh sách người dùng',
    status: 'Trạng thái',
    actions: 'Hành động',
    active: 'Hoạt động',
    unlock: 'Mở khóa',
    lock: 'Khóa',
    logout: 'Đăng xuất',
    back_to_app: 'Quay lại ứng dụng',
    login_success: 'Đăng nhập thành công!',
    register_success: 'Đăng ký thành công! Vui lòng đăng nhập.',
    user_exists: 'Tên đăng nhập đã tồn tại.',
    invalid_credentials: 'Sai tên đăng nhập hoặc mật khẩu.',
    fill_all_fields: 'Vui lòng điền đầy đủ thông tin.',
    admin_login_failed: 'Sai tên đăng nhập hoặc mật khẩu Admin.',
    confirm_lock: 'Khóa người dùng này?',
    confirm_delete_user: 'Xóa người dùng này?',
    change_admin_password: 'Hồ sơ (Cập nhật tài khoản)',
    new_password: 'Mật khẩu mới',
    save_password: 'Cập nhật',
    password_changed: 'Cập nhật tài khoản thành công!',
    current_feature: 'Tính năng đang dùng',
    last_activity: 'Hoạt động gần nhất',
    lock_duration: 'Thời gian khóa',
    select_lock_duration: 'Chọn thời gian khóa',
    duration_15m: '15 Phút',
    duration_1h: '1 Giờ',
    duration_1d: '1 Ngày',
    duration_3d: '3 Ngày',
    duration_7d: '1 Tuần',
    duration_30d: '1 Tháng',
    duration_permanent: 'Vĩnh viễn (100 năm)',
    cancel: 'Hủy',
    admin_locked: 'Admin khóa',
    admin_management: 'Quản lý Admin',
    create_admin: 'Tạo Admin',
    super_admin: 'Quản trị viên Cao cấp',
    normal_admin: 'Quản trị viên',
    role: 'Vai trò',
    audit_logs: 'Nhật ký hoạt động',
    log_action: 'Hành động',
    log_target: 'Đối tượng',
    log_timestamp: 'Thời gian',
    new_username: 'Tên đăng nhập mới',
    create_admin_success: 'Tạo Admin thành công.',
    admin_exists: 'Tên đăng nhập Admin đã tồn tại.',
    confirm_delete_admin: 'Xóa Admin này?',
    deleted_users: 'Người dùng đã xóa',
    restore: 'Khôi phục',
    deleted_by: 'Người xóa',
    locked_by: 'Người khóa',
    locked_by_admin: 'Khóa bởi Admin:',
    [Subject.MATH]: 'Toán học',
    [Subject.LITERATURE]: 'Ngữ văn',
    [Subject.PHYSICS]: 'Vật lý',
    [Subject.CHEMISTRY]: 'Hóa học',
    [Subject.BIOLOGY]: 'Sinh học',
    [Subject.HISTORY]: 'Lịch sử',
    [Subject.GEOGRAPHY]: 'Địa lý',
    [Subject.ENGLISH]: 'Tiếng Anh',
    [Subject.TECHNOLOGY]: 'Công nghệ',
    [Subject.CIVIC_EDUCATION]: 'Giáo dục công dân',
    [Subject.INFORMATICS]: 'Tin học',
    [Subject.NATURAL_SCIENCES]: 'Khoa học Tự nhiên',
    [LibraryItemType.SUMMARY]: 'Tóm tắt',
    [LibraryItemType.EXAM]: 'Đề thi',
    [LibraryItemType.REVIEW_EXERCISES]: 'Bài tập ôn',
    [LibraryItemType.SIMILAR_EXERCISES]: 'Bài tập tương tự',
  },
  [Language.ZH]: {
    slogan: '开启知识，塑造未来。',
    im_a: '我是...',
    student: '学生',
    teacher: '老师',
    select_goal: '选择你的目标',
    good_student: '好学生',
    excellent_student: '优秀学生',
    outstanding_student: '杰出学生',
    summarize: '总结',
    summarizer: '摘要器',
    exam_generator: '试卷生成器',
    ai_assistant: 'AI 助手',
    translator: '翻译器',
    slide_generator: '幻灯片生成器',
    learning_path: '学习路径',
    question_analysis: '问题分析',
    safety_guide: '安全指南',
    upload_file: '上传文件',
    file_placeholder: '上传文件（PDF, 图像, 音频, 视频）',
    choose_file: '选择文件',
    no_file_chosen: '未选择文件',
    generating: '生成中...',
    summary_placeholder: '您生成的摘要、思维导图和抽认卡将显示在此处。',
    mind_map: '思维导图',
    flashcards: '抽认卡',
    source_language: '源语言',
    target_language: '目标语言',
    source_text_placeholder: '输入要翻译的文本...',
    copy_text: '复制',
    copied: '已复制！',
    copy_as_text: '复制为文本',
    copy_for_word: '为 Word 复制',
    converting: '转换中...',
    swap_languages: '交换语言',
    translate_button: '翻译',
    presentation_topic: '演示主题',
    topic_placeholder: '例如，“人工智能的历史”',
    upload_template: '上传模板（可选）',
    generate_slides: '生成幻灯片',
    slide_placeholder: '您生成的幻灯片内容将显示在此处。',
    grade: '年级',
    subject: '学科',
    generate_plan: '生成计划',
    completed: '已完成',
    current_lesson: '当前课程',
    locked: '已锁定',
    plan_placeholder: '生成学习计划以开始。',
    lesson_placeholder: '选择一节课查看其内容。',
    mark_complete: '标记为完成并继续',
    exam_topic: '考试主题',
    multiple_choice: '多项选择',
    essay: '论述题',
    generate_exam: '生成试卷',
    exam_placeholder: '您生成的试题将显示在此处。',
    send_message: '发送',
    teacher_chatbot_greeting: '你好！我是你的AI学习伴侣。我将帮助你独立思考和解决问题。我将严格遵守2018年通识教育课程。今天你需要什么帮助？',
    teacher_chatbot_placeholder: '提出问题（例如，“我该如何解决这个问题？”，“解释这个概念”）...',
    attach_file: '附加文件',
    file_attached: '已附加文件:',
    remove_file: '删除文件',
    start_recording: '开始录音',
    stop_recording: '停止录音',
    voice_unsupported: '您的浏览器不支持语音输入。',
    select_dialect: '选择方言',
    north: '北',
    central: '中',
    south: '南',
    textbook: '教科书',
    upload_matrix: '上传矩阵',
    manual_textbook_placeholder: '输入教科书名称...',
    question_analysis_title: '类似练习生成器',
    generate_similar_exercises: '生成类似练习',
    upload_question_file: '上传问题文件（图片、PDF）',
    similar_exercises_placeholder: '您生成的类似练习将显示在此处。',
    analysis_of_original_question: '原始问题分析',
    similar_practice_exercises: '类似练习题',
    read_aloud: '朗读',
    exam_duration: '考试时间（分钟）',
    num_multiple_choice: '选择题总数',
    num_essay: '按难度分列的论述题',
    difficulty_level: '难度级别',
    recognition: '认识',
    comprehension: '理解',
    application: '应用',
    mc_difficulty_breakdown: '按难度分列的选择题',
    mc_sum_error: '选择题各难度数量总和必须等于总数。',
    review_topic: '复习主题',
    generate_review_exercises: '生成练习',
    review_placeholder: '您生成的复习练习将显示在此处。',
    go_home: '返回首页',
    library: '图书馆',
    documents: '文件',
    save_to_library: '保存到图书馆',
    save_to_documents: '保存到文件',
    saved: '已保存!',
    library_empty: '你的图书馆是空的。保存生成的内容以在此处查看。',
    documents_empty: '您没有已保存的文档。保存生成的内容以在此处查看。',
    delete: '删除',
    view: '查看',
    close: '关闭',
    confirm_delete_title: '确认删除',
    confirm_delete_message: '你确定要删除这个项目吗？',
    storage_full: '存储已满。请删除一些项目以保存新内容。',
    storage_usage: '存储使用情况',
    item_name_placeholder: '为此项目输入名称...',
    save: '保存',
    zoom_in: '放大',
    zoom_out: '缩小',
    reset_zoom: '重置缩放',
    specialized_review: '专题复习',
    numbers: '数与代数',
    geometry: '几何',
    both: '两者皆是',
    sub_subjects: '子学科',
    none: '无',
    canh_dieu: 'Cánh diều',
    chan_troi_sang_tao: 'Chân trời sáng创造',
    ket_noi_tri_thuc: 'Kết nối tri thức',
    other: '其他（手动输入）',
    image_generation_error: '图片生成失败',
    unsafe_content_error: '此内容不适合学习目的。请提出另一个问题。',
    terms_title: '使用承诺',
    terms_content: '我承诺使用人工智能辅助学习，不作弊、不抄袭，不输入个人信息。',
    i_agree: '我同意',
    continue: '开始使用',
    account_locked_title: '账户已锁定',
    account_locked_message: '您的帐户已被管理员锁定。',
    lock_mild_message: '由于安全违规，您的帐户被暂时锁定 3 天。',
    lock_severe_message: '由于严重违规（例如，索要密码、作弊），您的帐户被锁定 1 个月。',
    unlock_at: '解锁时间：',
    contact_support: '刷新页面',
    safety_guide_title: '学会正确使用 AI',
    sg_topic_1: '有效提问',
    sg_desc_1: '探究思维',
    sg_topic_2: '为什么不抄袭',
    sg_desc_2: '反对死记硬背',
    sg_topic_3: '事实核查',
    sg_desc_3: '打击假新闻',
    sg_topic_4: '数据隐私',
    sg_desc_4: '网络安全',
    ethics_reminder: '\n\n*注意：此建议仅供参考。请根据自己的理解重写，并在使用时注明出处。*',
    login: '登录',
    register: '注册',
    username: '用户名',
    password: '密码',
    admin_password: '管理员密码',
    enter_admin_mode: '进入管理员模式',
    admin_dashboard: '管理员仪表板',
    user_list: '用户列表',
    status: '状态',
    actions: '操作',
    active: '活跃',
    unlock: '解锁',
    lock: '锁定',
    logout: '登出',
    back_to_app: '返回应用',
    login_success: '登录成功！',
    register_success: '注册成功！请登录。',
    user_exists: '用户名已存在。',
    invalid_credentials: '用户名或密码无效。',
    fill_all_fields: '请填写所有字段。',
    admin_login_failed: '管理员凭据无效。',
    confirm_lock: '锁定该用户？',
    confirm_delete_user: '删除该用户？',
    change_admin_password: '我的资料（更新凭据）',
    new_password: '新密码',
    save_password: '更新',
    password_changed: '凭据更新成功！',
    current_feature: '当前功能',
    last_activity: '上次活动',
    lock_duration: '锁定时间',
    select_lock_duration: '选择锁定时间',
    duration_15m: '15 分钟',
    duration_1h: '1 小时',
    duration_1d: '1 天',
    duration_3d: '3 天',
    duration_7d: '1 周',
    duration_30d: '1 个月',
    duration_permanent: '永久 (100年)',
    cancel: '取消',
    admin_locked: '管理员锁定',
    admin_management: '管理员管理',
    create_admin: '创建管理员',
    super_admin: '超级管理员',
    normal_admin: '管理员',
    role: '角色',
    audit_logs: '审计日志',
    log_action: '操作',
    log_target: '目标',
    log_timestamp: '时间',
    new_username: '新用户名',
    create_admin_success: '管理员创建成功。',
    admin_exists: '管理员用户名已存在。',
    confirm_delete_admin: '删除此管理员？',
    deleted_users: '已删除的用户',
    restore: '恢复',
    deleted_by: '删除者',
    locked_by: '锁定者',
    locked_by_admin: '管理员锁定:',
    [Subject.MATH]: '数学',
    [Subject.LITERATURE]: '文学',
    [Subject.PHYSICS]: '物理',
    [Subject.CHEMISTRY]: '化学',
    [Subject.BIOLOGY]: '生物学',
    [Subject.HISTORY]: '历史',
    [Subject.GEOGRAPHY]: '地理',
    [Subject.ENGLISH]: '英语',
    [Subject.TECHNOLOGY]: '技术',
    [Subject.CIVIC_EDUCATION]: '公民教育',
    [Subject.INFORMATICS]: '信息学',
    [Subject.NATURAL_SCIENCES]: '自然科学',
    [LibraryItemType.SUMMARY]: '摘要',
    [LibraryItemType.EXAM]: '考试',
    [LibraryItemType.REVIEW_EXERCISES]: '复习练习',
    [LibraryItemType.SIMILAR_EXERCISES]: '类似练习',
  },
  [Language.FR]: {
    slogan: 'Débloquer la connaissance, façonner l\'avenir.',
    im_a: 'Je suis...',
    student: 'Étudiant(e)',
    teacher: 'Enseignant(e)',
    select_goal: 'Sélectionnez votre objectif',
    good_student: 'Bon Élève',
    excellent_student: 'Excellent Élève',
    outstanding_student: 'Élève Exceptionnel',
    summarize: 'Résumer',
    summarizer: 'Résumeur',
    exam_generator: 'Générateur d\'examen',
    ai_assistant: 'Assistant IA',
    translator: 'Traducteur',
    slide_generator: 'Générateur de diapositives',
    learning_path: 'Parcours d\'apprentissage',
    question_analysis: 'Analyse de question',
    safety_guide: 'Guide de Sécurité',
    upload_file: 'Télécharger un fichier',
    file_placeholder: 'Télécharger un fichier (PDF, image, audio, vidéo)',
    choose_file: 'Choisir un fichier',
    no_file_chosen: 'Aucun fichier choisi',
    generating: 'Génération...',
    summary_placeholder: 'Votre résumé, votre carte mentale et vos flashcards générés apparaîtront ici.',
    mind_map: 'Carte Mentale',
    flashcards: 'Flashcards',
    source_language: 'Langue source',
    target_language: 'Langue cible',
    source_text_placeholder: 'Saisissez le texte à traduire...',
    copy_text: 'Copier',
    copied: 'Copié !',
    copy_as_text: 'Copier en texte',
    copy_for_word: 'Copier pour Word',
    converting: 'Conversion...',
    swap_languages: 'Inverser les langues',
    translate_button: 'Traduire',
    presentation_topic: 'Sujet de la présentation',
    topic_placeholder: 'par exemple, "L\'histoire de l\'IA"',
    upload_template: 'Télécharger un modèle (facultatif)',
    generate_slides: 'Générer les diapositives',
    slide_placeholder: 'Le contenu de votre diapositive générée apparaîtra ici.',
    grade: 'Classe',
    subject: 'Matière',
    generate_plan: 'Générer un plan',
    completed: 'Terminé',
    current_lesson: 'Leçon actuelle',
    locked: 'Verrouillé',
    plan_placeholder: 'Générez un plan d\'apprentissage pour commencer.',
    lesson_placeholder: 'Sélectionnez une leçon pour voir son contenu.',
    mark_complete: 'Marquer comme terminé et suivant',
    exam_topic: 'Sujet de l\'examen',
    multiple_choice: 'Choix multiple',
    essay: 'Dissertation',
    generate_exam: 'Générer l\'examen',
    exam_placeholder: 'Vos questions d\'examen générées apparaîtront ici.',
    send_message: 'Envoyer',
    teacher_chatbot_greeting: 'Bonjour ! Je suis votre compagnon d\'étude IA. Je vous aiderai à réfléchir et à résoudre des problèmes par vous-même. Je respecterai strictement le programme d\'enseignement général de 2018. En quoi puis-je vous aider aujourd\'hui ?',
    teacher_chatbot_placeholder: 'Posez une question (par exemple : "Comment résoudre ceci ?", "Expliquez ce concept")...',
    attach_file: 'Joindre un fichier',
    file_attached: 'Fichier joint:',
    remove_file: 'Supprimer le fichier',
    start_recording: 'Commencer l\'enregistrement',
    stop_recording: 'Arrêter l\'enregistrement',
    voice_unsupported: 'La saisie vocale n\'est pas prise en charge par votre navigateur.',
    select_dialect: 'Sélectionner un dialecte',
    north: 'Nord',
    central: 'Centre',
    south: 'Sud',
    textbook: 'Manuel scolaire',
    upload_matrix: 'Télécharger la matrice',
    manual_textbook_placeholder: 'Entrez le nom du manuel...',
    question_analysis_title: 'Générateur d\'Exercices Similaires',
    generate_similar_exercises: 'Générer des exercices similaires',
    upload_question_file: 'Télécharger un fichier de question (image, PDF)',
    similar_exercises_placeholder: 'Vos exercices similaires générés apparaîtront ici.',
    analysis_of_original_question: 'Analyse de la question originale',
    similar_practice_exercises: 'Exercices similaires',
    read_aloud: 'Lire à voix haute',
    exam_duration: 'Durée de l\'examen (minutes)',
    num_multiple_choice: 'Total QCM',
    num_essay: 'Dissertations par difficulté',
    difficulty_level: 'Niveau de difficulté',
    recognition: 'Reconnaissance',
    comprehension: 'Comprehension',
    application: 'Application',
    mc_difficulty_breakdown: 'QCM par difficulté',
    mc_sum_error: 'La somme des QCM doit correspondre au total.',
    review_topic: 'Sujet de révision',
    generate_review_exercises: 'Générer les exercices',
    review_placeholder: 'Vos exercices de révision générés apparaîtront ici.',
    go_home: 'Retour à l\'accueil',
    library: 'Bibliothèque',
    documents: 'Documents',
    save_to_library: 'Sauvegarder dans la Bibliothèque',
    save_to_documents: 'Sauvegarder dans les Documents',
    saved: 'Sauvegardé !',
    library_empty: 'Votre bibliothèque est vide. Enregistrez le contenu généré pour le voir ici.',
    documents_empty: 'Vous n\'avez aucun document enregistré. Enregistrez le contenu généré pour le voir ici.',
    delete: 'Supprimer',
    view: 'Voir',
    close: 'Fermer',
    confirm_delete_title: 'Confirmer la suppression',
    confirm_delete_message: 'Êtes-vous sûr de vouloir supprimer cet élément ?',
    storage_full: 'Le stockage est plein. Veuillez supprimer certains éléments pour enregistrer du nouveau contenu.',
    storage_usage: 'Utilisation du stockage',
    item_name_placeholder: 'Entrez un nom pour cet élément...',
    save: 'Sauvegarder',
    zoom_in: 'Zoom avant',
    zoom_out: 'Zoom arrière',
    reset_zoom: 'Réinitialiser le zoom',
    specialized_review: 'Révision Spécialisée',
    numbers: 'Nombres et Algèbre',
    geometry: 'Géométrie',
    both: 'Les deux',
    sub_subjects: 'Sous-matières',
    none: 'Aucun',
    canh_dieu: 'Cánh diều',
    chan_troi_sang_tao: 'Chân trời sáng tạo',
    ket_noi_tri_thuc: 'Kết nối tri thức',
    other: 'Autre (saisie manuelle)',
    image_generation_error: 'Échec de la génération d\'image',
    unsafe_content_error: 'Ce contenu n\'est pas adapté à des fins d\'apprentissage. Veuillez poser une autre question.',
    terms_title: 'Engagement d\'utilisation',
    terms_content: 'Je m\'engage à utiliser l\'IA pour soutenir l\'apprentissage, à ne pas tricher, à ne pas copier et à ne pas saisir d\'informations personnelles.',
    i_agree: 'J\'accepte',
    continue: 'Commencer',
    account_locked_title: 'Compte verrouillé',
    account_locked_message: 'Votre compte a été verrouillé par l\'administrateur.',
    lock_mild_message: 'Votre compte est temporairement verrouillé pendant 3 jours pour des infractions de sécurité.',
    lock_severe_message: 'Votre compte est verrouillé pendant 1 mois pour des infractions graves (ex. : demande de mots de passe, tricherie).',
    unlock_at: 'Déverrouillage à :',
    contact_support: 'Recharger la page',
    safety_guide_title: 'Apprendre à utiliser l\'IA correctement',
    sg_topic_1: 'Questionnement efficace',
    sg_desc_1: 'Pensée & Enquête',
    sg_topic_2: 'Pourquoi ne pas copier ?',
    sg_desc_2: 'Anti-apprentissage par cœur',
    sg_topic_3: 'Vérification des faits',
    sg_desc_3: 'Anti-désinformation',
    sg_topic_4: 'Confidentialité des données',
    sg_desc_4: 'Cybersécurité',
    ethics_reminder: '\n\n*Remarque : Cette suggestion est uniquement pour référence. Réécrivez-la selon votre propre compréhension et citez les sources si utilisées.*',
    login: 'Connexion',
    register: 'S\'inscrire',
    username: 'Nom d\'utilisateur',
    password: 'Mot de passe',
    admin_password: 'Mot de passe Admin',
    enter_admin_mode: 'Mode Admin',
    admin_dashboard: 'Tableau de bord Admin',
    user_list: 'Liste des utilisateurs',
    status: 'Statut',
    actions: 'Actions',
    active: 'Actif',
    unlock: 'Déverrouiller',
    lock: 'Verrouiller',
    logout: 'Déconnexion',
    back_to_app: 'Retour à l\'application',
    login_success: 'Connexion réussie !',
    register_success: 'Inscription réussie ! Veuillez vous connecter.',
    user_exists: 'Le nom d\'utilisateur existe déjà.',
    invalid_credentials: 'Nom d\'utilisateur ou mot de passe invalide.',
    fill_all_fields: 'Veuillez remplir tous les champs.',
    admin_login_failed: 'Identifiants Admin invalides.',
    confirm_lock: 'Verrouiller cet utilisateur ?',
    confirm_delete_user: 'Supprimer cet utilisateur ?',
    change_admin_password: 'Mon Profil (Mettre à jour)',
    new_password: 'Nouveau mot de passe',
    save_password: 'Mettre à jour',
    password_changed: 'Identifiants mis à jour !',
    current_feature: 'Fonctionnalité actuelle',
    last_activity: 'Dernière activité',
    lock_duration: 'Durée du verrouillage',
    select_lock_duration: 'Sélectionner la durée',
    duration_15m: '15 Minutes',
    duration_1h: '1 Heure',
    duration_1d: '1 Jour',
    duration_3d: '3 Jours',
    duration_7d: '1 Semaine',
    duration_30d: '1 Mois',
    duration_permanent: 'Permanent',
    cancel: 'Annuler',
    admin_locked: 'Verrouillé par Admin',
    admin_management: 'Gestion des Admins',
    create_admin: 'Créer Admin',
    super_admin: 'Super Admin',
    normal_admin: 'Admin',
    role: 'Rôle',
    audit_logs: 'Journaux d\'audit',
    log_action: 'Action',
    log_target: 'Cible',
    log_timestamp: 'Temps',
    new_username: 'Nouveau nom d\'utilisateur',
    create_admin_success: 'Admin créé avec succès.',
    admin_exists: 'Ce nom d\'utilisateur admin existe déjà.',
    confirm_delete_admin: 'Supprimer cet admin ?',
    deleted_users: 'Utilisateurs supprimés',
    restore: 'Restaurer',
    deleted_by: 'Supprimé par',
    locked_by: 'Verrouillé par',
    locked_by_admin: 'Verrouillé par Admin :',
    [Subject.MATH]: 'Mathématiques',
    [Subject.LITERATURE]: 'Littérature',
    [Subject.PHYSICS]: 'Physique',
    [Subject.CHEMISTRY]: 'Chimie',
    [Subject.BIOLOGY]: 'Biologie',
    [Subject.HISTORY]: 'Histoire',
    [Subject.GEOGRAPHY]: 'Géographie',
    [Subject.ENGLISH]: 'Anglais',
    [Subject.TECHNOLOGY]: 'Technologie',
    [Subject.CIVIC_EDUCATION]: 'Éducation Civique',
    [Subject.INFORMATICS]: 'Informatique',
    [Subject.NATURAL_SCIENCES]: 'Sciences Naturelles',
    [LibraryItemType.SUMMARY]: 'Résumé',
    [LibraryItemType.EXAM]: 'Examen',
    [LibraryItemType.REVIEW_EXERCISES]: 'Exercices de révision',
    [LibraryItemType.SIMILAR_EXERCISES]: 'Exercices similaires',
  }
};